### PR TITLE
feat: support consider lgtm-like comment as review

### LINKED ISSUE #38: Use the comment containing lgtm as a review to update the last review time of PR.
## Feature Request

- [x] I have searched the issues of this repository and believe that this is not a duplicate.

### Describe the feature you'd like:

If the comment of the PR contains `/lgtm` command, then it is also considered a review, and the last review time of the PR will be updated based on this judgment.

### PR DESCRIPTION
**Pull request by Mini256**
## CheckedList
- [x] feat: support consider lgtm-like comment as review
- [x] update publish workflow 

## Related
close #38

### CODE REVIEW

**Comment by hi-rustin** [comment]
@Mini256  Why we need this?

**Comment by Mini256** [comment]
> @Mini256 Why we need this?

Because the user may only enter the comment of `/lgtm`, but he actually completed the review process.

**Comment by Mini256** [comment]
It‘s a TODO item in the github-tool source code.
image

**Comment by hi-rustin** [comment]
> It‘s a TODO item in the github-tool source code.
> 
> image

Maybe we shouldn't count that way at the moment. Because some people's /lgtm may be invalid.

**Comment by hi-rustin** [comment]
Actually, I don't know what the point of this record is?It's pretty much useless as it stands and would break the ability to persist GitHub reviews.

**Comment by Mini256** [comment]
> Actually, I don't know what the point of this record is?It's pretty much useless as it stands and would break the ability to persist GitHub reviews.

The last review time will not affect the persist of GitHub reviews.

**Comment by hi-rustin** [comment]
> The last review time will not affect the persist of GitHub reviews.

Got it. But there still seems to be an invalid /lgtm problem?

**Comment by Mini256** [comment]
> Got it. But there still seems to be an invalid /lgtm problem?

Indeed.

**Pull request closed without merging**
